"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.typeDefs = void 0;
// const {gql} = require('apollo-server');
var apollo_server_1 = require("apollo-server");
exports.typeDefs = (0, apollo_server_1.gql)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n\ninput TaskInput {\n    _id :String\n    title :String! \n    description: String! \n    estimatedTime: Float! \n    status: String! \n    priority: String!\n    untilDate: String\n    review: String\n    timeSpent: Float\n}\n\ntype Task { \n    _id: String! \n    title :String! \n    description: String! \n    estimatedTime: Float! \n    status: String! \n    priority: String!\n    untilDate: String\n    review: String\n    timeSpent: Float\n}\n\ninput Filters { \n    status: [String]\n    priority: [String]\n}\n\ntype Query {\n    tasks: [Task!]!\n    tasksByKeywordAndFilters(keyword: String, filters: Filters): [Task]\n}\n\ntype Mutation {\n    createTask(taskInput: TaskInput): Task\n    deleteTask(_id: String!): Task\n    updateTask(taskInput: TaskInput): Task\n\n}\n\ntype Subscription {\n    taskCreated: Task\n    taskDeleted: String\n    taskUpdated: Task\n}\n\n"], ["\n\ninput TaskInput {\n    _id :String\n    title :String! \n    description: String! \n    estimatedTime: Float! \n    status: String! \n    priority: String!\n    untilDate: String\n    review: String\n    timeSpent: Float\n}\n\ntype Task { \n    _id: String! \n    title :String! \n    description: String! \n    estimatedTime: Float! \n    status: String! \n    priority: String!\n    untilDate: String\n    review: String\n    timeSpent: Float\n}\n\ninput Filters { \n    status: [String]\n    priority: [String]\n}\n\ntype Query {\n    tasks: [Task!]!\n    tasksByKeywordAndFilters(keyword: String, filters: Filters): [Task]\n}\n\ntype Mutation {\n    createTask(taskInput: TaskInput): Task\n    deleteTask(_id: String!): Task\n    updateTask(taskInput: TaskInput): Task\n\n}\n\ntype Subscription {\n    taskCreated: Task\n    taskDeleted: String\n    taskUpdated: Task\n}\n\n"])));
var templateObject_1;
